[general]
db_timeout = 900.0
db_path = "./vault_db.toml"
pass_gen_letter_count = 13.0
preset_fields = [
    [
    0,
    "Custom",
    "",
    "SecretLine",
],
    [
    1,
    "Username",
    "Username",
    "SecretLine",
],
    [
    2,
    "Password",
    "Password",
    "SecretLine",
],
    [
    3,
    "Website",
    "Url",
    "Url",
],
    [
    4,
    "Notes",
    "Notes",
    "TextLine",
],
]

[general.window_settings]
sidebar_width = 140.0
window_size = [
    800.0,
    350.0,
]
